### ISSUE TITLE
"Your interested topics" fields in the registration form not working 

### ISSUE THREAD

**Issue by zhaojin42** [nusskylab/nusskylab#514]
The keywords (tags) are not displayed upon clicking the fields.

**Comment by knmnyn** [comment]
Hi all:  The briefing for Orbital '17 is next week and the reg form is broken.  Can you try to fix it?  Talk among yourselves to see who can take ownership of the issue.  Thanks!

**Comment by njyjn** [comment]
Hi prof,
May I suggest that we revert the recent merge back to the last stable version? I noticed a few changes that @leminphuc could have made that are causing many issues, such as user roles tab not appearing, CSS padding off. The choices are not showing up possibly due to that too. Will look at it asap (sorry; having midterms). In the meanwhile will be good to have a stable version live. Tks. 
Get Outlook for iOS




On Wed, Mar 1, 2017 at 11:33 AM +0800, "Min-Yen Kan" <notifications@github.com> wrote:












Hi all:  The briefing for Orbital '17 is next week and the reg form is broken.  Can you try to fix it?  Talk among yourselves to see who can take ownership of the issue.  Thanks!

**Comment by njyjn** [comment]
Hi @zhaojin42, can I check if you were able to edit the question-form in the survey templates page? I am unable to edit or create any questions.

<img width="1145" alt="screen shot 2017-03-01 at 12 47 27" src="https://cloud.githubusercontent.com/assets/10694375/23446340/5bf2d996-fe7d-11e6-82c8-aeb033c50916.png">

I suspect that no options were entered into the question, so the user is presented with a blank box. Could be the case. Pls. help try on your end. Thanks.

**Comment by zhaojin42** [comment]
Are you referring to the form "Milestone 1 --> survey_type_registration"? 

I tried to create a question in that form but there is no response after I (filled in the information for the question and) clicked the "Create Question" button.

**Comment by njyjn** [comment]
That could be the issue. How was the registration form for 2017 first created then? 

I'll see what we can do about the buttons.

**Comment by zhaojin42** [comment]
The registration form from 2016 was fine so I did not create a new one for 2017. I think the code of the form is somewhere in the database.

**Comment by njyjn** [comment]
Hmm, the 2016 form also has blank user topics... We may have to manually add in the topics into the database if the buttons issue doesn't work. It's coded in JavaScript at `app/assets/javascripts/survey_templates.js`, anyone good at JS?

**Comment by zhaojin42** [comment]
I remember the form was working fine before the website was updated / restarted at the end of last month. *_*

**Comment by njyjn** [comment]
> Hi prof,
> May I suggest that we revert the recent merge back to the last stable version? I noticed a few changes that the previous PR could have made that are causing many issues, such as user roles tab not appearing, CSS padding off. Will look at it asap (sorry; having midterms). In the meanwhile will be good to have a stable version live. Tks.

@knmnyn is it possible to revert to the last stable version? ie before #509 at master/ 2538dba75981d0f3603bcad96d249fa7c662bb91

**Comment by le-minhphuc** [comment]
Dear Prof,

Sorry for the late reply. I think the last merge was the merge from my pull
request. My computer hardware was down for about a week and I had sent it
for reparation recently so I wouldn't be able to fix the bug (if that's
created by my code) soon. I think the best solution now is as Justin
mentioned - to undo the most recent merge from my pull request to see if
the feature works.

Minh Phuc

On Wed, 1 Mar 2017 at 10:06 PM, zhaojin42 <notifications@github.com> wrote:

I remember the form was working fine before the website was updated /
restarted at the end of last month. *_*

—
You are receiving this because you were assigned.


Reply to this email directly, view it on GitHub
<https://github.com/nusskylab/nusskylab/issues/514#issuecomment-283347424>,
or mute the thread

**Comment by njyjn** [comment]
Quick fix will be to manually enter the '''[option 1][option2]''' into the field in the database representing the question.

**Comment by zhaojin42** [comment]
Nope. I don't have the access to the database. Do we still have those lists of keywords in the database or have we lost them in the recent update?

If we still have those lists, please help to retrieve them, re-populate the new form and make sure the new form is ready by the end of tomorrow.

Thanks a lot!

**Comment by knmnyn** [comment]
Hi all:

I will try to deal with these issues tonight.  Wish me luck!


Cheers,

Min

--
Min-Yen KAN (Dr) :: Associate Professor :: National University of Singapore
:: NUS School of Computing, AS6 05-12, 13 Computing Drive
Singapore 117417 :: +65 6516 1885(DID) :: +65 6779 4580 (Fax) ::
kanmy@comp.nus.edu.sg (E) :: www.comp.nus.edu.sg/~kanmy (W)

**Comment by ylhlh** [comment]
Hi, regarding the buttons, it seems like an autolink issue, after I deleted the line 
//= require public_views/jquery.js from app/assets/javascripts/application.js, the buttons are now working

**Comment by ylhlh** [comment]
Yes the blank box should be because no options were input, after fixing the buttons, edit the registration form and put ["option 1", "option 2"] as the options and it should work

**Comment by knmnyn** [comment]
Hi Yong Lin:

Sorry, I'm not sure which PRs and revisions I should be merging for the
codebase to make the system start working again?  Can you clarify?  I saw
another PR in a different branch #515 in addition to the conversation in
this thread..

Thanks!

Cheers,

Min

--
Min-Yen KAN (Dr) :: Associate Professor :: National University of Singapore
:: NUS School of Computing, AS6 05-12, 13 Computing Drive
Singapore 117417 :: +65 6516 1885(DID) :: +65 6779 4580 (Fax) ::
kanmy@comp.nus.edu.sg (E) :: www.comp.nus.edu.sg/~kanmy (W)

**Comment by ylhlh** [comment]
Hi Prof Min, you can merge the PR, the PR makes it possible to edit fields in the registration form through skylab. However for some reason, it seems that currently the registration forms have blank options, even the past year ones, so we might have to add the options in manually to fix this issue.

**Comment by ylhlh** [comment]
Ok the keywords are displaying. But there are a few blank questions in the form

**Comment by knmnyn** [comment]
Ok, I think the form should be working as is again.  Can we all check?


Cheers,

Min

--
Min-Yen KAN (Dr) :: Associate Professor :: National University of Singapore
:: NUS School of Computing, AS6 05-12, 13 Computing Drive
Singapore 117417 :: +65 6516 1885(DID) :: +65 6779 4580 (Fax) ::
kanmy@comp.nus.edu.sg (E) :: www.comp.nus.edu.sg/~kanmy (W)

**Comment by njyjn** [comment]
Great work, @ylhlh, tags are working and forms are now editable. Has it anything to do with @le-minhphuc's pull request? Otherwise I'll go through it with him to see what needs to be rectified. Thanks.

**Comment by ylhlh** [comment]
Hi @njyjn, yes it is caused by his PR. In particular, addition/moving of css files: 3-col-portfolio and/or thumbnail gallery caused the css paddings to be off (The bottom padding is not yet fixed but I suspect its an easy fix), and inclusion of an additional jquery require in application.js caused the autolink require to somehow be blocked. Maybe you can check with him on the rationale for including 2 of the same dependencies in app/assets/javascripts/application.js : jquery and bootstrap. Thanks!

**Comment by zhaojin42** [comment]
@knmnyn Thanks a lot! I have create a user to test the form and it works fine.
I will announce to the students that the registration of interest opens tomorrow.

**Comment by njyjn** [comment]
> Hi @njyjn, yes it is caused by his PR. In particular, addition/moving of css files: 3-col-portfolio and/or thumbnail gallery caused the css paddings to be off (The bottom padding is not yet fixed but I suspect its an easy fix), and inclusion of an additional jquery require in application.js caused the autolink require to somehow be blocked. Maybe you can check with him on the rationale for including 2 of the same dependencies in app/assets/javascripts/application.js : jquery and bootstrap. Thanks!

@le-minhphuc may I check if the following is necessary?

```
In app/assets/javascripts/application.js Mark as resolved 
//= require public_views/bootstrap.js
//= require public_views/bootstrap.min.js
//= require public_views/modalbox.js
```

**Comment by ylhlh** [comment]
Only the statement in the application.js, I did not delete the actual file

**Comment by le-minhphuc** [comment]
@njyjn I used to put the javascript files under public_views, but later I realized that Rails allows loading javascript assets from app/assets/javascripts. In short the lines you mentioned are not necessary. I should have deleted them.
Regarding the actual file I have moved them to the assets/javascript/public_views folder.
